name: Ping test

on:
  schedule:
    - cron: '15 9,21 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - id: ping
        run: curl --no-progress-meter https://oshdev.com | grep -c '<title>Osh was here o/</title>' &> /dev/null
      - name: notify
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_MESSAGE: "ref: ${{ github.ref }},\n sha: ${{ github.sha}},\n outcome: ${{steps.ping.outcome}}"
        run: |
          curl -X POST --data-urlencode "payload={\
            \"channel\": \"$SLACK_CHANNEL_ID\",\
            \"username\": \"GitHub Actions Bot\",\
            \"text\": \"$SLACK_MESSAGE\"\
          }" $SLACK_WEBHOOK
